### ISSUE TITLE
I get this error: 'undefined method `each' for nil:NilClass'  when I start flavored_gherkin

### ISSUE THREAD

**Issue by JohnBat26** [rajatthareja/FlavoredGherkin#1]
Hello.
Thanks for your pretty gem!
But I don't start it. I get error:
```
flavored_gherkin -t 'My Features' -f './features' -o './export_features'
(erb):3:in `block (4 levels) in build': undefined method `each' for nil:NilClass (NoMethodError)
        from /home/johnbat26/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/erb.rb:864:in `eval'
        from /home/johnbat26/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/erb.rb:864:in `result'
        from (erb):14:in `block (4 levels) in build'
        from (erb):13:in `each'
        from (erb):13:in `block (3 levels) in build'
        from /home/johnbat26/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/erb.rb:864:in `eval'
        from /home/johnbat26/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/erb.rb:864:in `result'
        from (erb):20:in `block (3 levels) in build'
        from (erb):17:in `each'
        from (erb):17:in `each_with_index'
        from (erb):17:in `block (2 levels) in build'
        from (erb):15:in `each'
        from (erb):15:in `each_with_index'
        from (erb):15:in `block in build'
        from /home/johnbat26/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/erb.rb:864:in `eval'
        from /home/johnbat26/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/erb.rb:864:in `result'
        from (erb):41:in `block in build'
        from /home/johnbat26/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/erb.rb:864:in `eval'
        from /home/johnbat26/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/erb.rb:864:in `result'
        from /home/johnbat26/.rvm/gems/ruby-2.3.4/gems/flavored_gherkin-0.2/lib/flavored_gherkin/html_flavour.rb:16:in `block in build'
        from /home/johnbat26/.rvm/gems/ruby-2.3.4/gems/flavored_gherkin-0.2/lib/flavored_gherkin/html_flavour.rb:15:in `open'
        from /home/johnbat26/.rvm/gems/ruby-2.3.4/gems/flavored_gherkin-0.2/lib/flavored_gherkin/html_flavour.rb:15:in `build'
        from /home/johnbat26/.rvm/gems/ruby-2.3.4/gems/flavored_gherkin-0.2/lib/flavored_gherkin.rb:130:in `build'
        from /home/johnbat26/.rvm/gems/ruby-2.3.4/gems/flavored_gherkin-0.2/bin/flavored_gherkin:47:in `<top (required)>'
        from /home/johnbat26/.rvm/gems/ruby-2.3.4/bin/flavored_gherkin:23:in `load'
        from /home/johnbat26/.rvm/gems/ruby-2.3.4/bin/flavored_gherkin:23:in `<main>'
        from /home/johnbat26/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
        from /home/johnbat26/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by rajatthareja** [comment]
Could you please share one of your feature file, with which I can reproduce error.

**Comment by JohnBat26** [comment]
https://www.dropbox.com/s/6qy16za5h4istwd/move_activity_to_other_operator.feature?dl=0
https://www.dropbox.com/s/xecanh1m219dohc/anon_create_activity.feature?dl=0

**Comment by rajatthareja** [comment]
@JohnBat26 The above feature files just works fine. 

![features_ru](https://user-images.githubusercontent.com/16877986/33525497-a4c90eca-d856-11e7-9023-7d24ee0b6c4a.png)

Please try to find the feature file for which gem is throwing the error, and share it with me. 

Or you can send me your entire features folder at mail@rajatthareja.com if its fine with you.
